version: '3.8'
services:
  mysql-db:
    image: mysql:8.0.3
    environment:
      MYSQL_DATABASE: 'jarspeed'
      MYSQL_USER: 'clientmysqljarspeed'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo-db:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  spring-boot-api:
    build: ./
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_DB: 'jarspeed'
      MYSQL_USER: 'clientmysqljarspeed'
      MYSQL_PASSWORD: 'password'
      MONGO_HOST: mongo-db
      MONGO_DB: 'nom_db_mongo'
      MONGO_USER: 'mongouser'
      MONGO_PASSWORD: 'mongopassword'
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - mongo-db

volumes:
  mysql-data:
  mongo-data:
