#Clé de chiffrement
jwt.key=1D92EC9A7FE6A599D63EC324AAC6BA378958531728247A507E46B44E9F

#Connexion MySql
spring.datasource.url=http://localhost:3306/
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#MongoDB
spring.data.mongodb.uri=mongodb://mongouser:mongopassword@mongo-db:27017/nom_db_mongo

