#Clé de chiffrement
jwt.key=1D92EC9A7FE6A599D63EC324AAC6BA378958531728247A507E46B44E9F

#Connexion MySql
spring.datasource.url=jdbc:mysql://mysql-db:3306/ma_base_de_donnees
spring.datasource.username=utilisateur
spring.datasource.password=motdepasse
spring.jpa.hibernate.ddl-auto=update

#MongoDB
spring.data.mongodb.uri=mongodb://mongouser:mongopassword@mongo-db:27017/nom_db_mongo

