CREATE DATABASE IF NOT EXISTS `jarspeed`;

USE `jarspeed`;

CREATE TABLE `SEX` (
  `ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL
);

CREATE TABLE `USER` (
  `LASTNAME` varchar(255) NOT NULL,
  `FIRSTNAME` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `AGE` int(11) NOT NULL,
  `SEX` int(11) NOT NULL,
  `WEIGHT` double NOT NULL,
  `PASSWORD` varchar(255) NOT NULL
);

ALTER TABLE `SEX`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `USER`
  ADD PRIMARY KEY (`EMAIL`),
  ADD KEY `SEX` (`SEX`);

ALTER TABLE `SEX`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `USER`
  ADD CONSTRAINT `USER_ibfk_1` FOREIGN KEY (`SEX`) REFERENCES `SEX` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;


INSERT INTO USER (LASTNAME, FIRSTNAME, EMAIL, AGE, SEX, WEIGHT, PASSWORD)
VALUES ('TEST','test','test',12,1,1.5,'testtt');

